development:
  adapter: postgresql
  database: internal_mess_tracker
  host: localhost
  username: postgres
  password: postgres

production:
  adapter: postgresql
  database: internal_mess_tracker_db
  host: dpg-cotlh0i1hbls73aacru0-a
  url: postgres://internal_mess_tracker_db_user:ERZpLk4Xkx2MdVdvH61boIi58plPXgVG@dpg-cotlh0i1hbls73aacru0-a/internal_mess_tracker_db
  username: internal_mess_tracker_db_user
  password: ERZpLk4Xkx2MdVdvH61boIi58plPXgVG